<!DOCTYPE html>
<html>
<head>
    <title>Ext JS And ZendFramewrk 1</title>
    <!-- Ext JS Files -->
    <link rel="stylesheet" type="text/css" href="extjs/resources/css/ext-all.css">
    <script type="text/javascript" src="extjs/ext-all-debug.js"></script>
    
    <!-- App Files -->
    <link rel="stylesheet" type="text/css" href="resources/css/app.css">
    <script type="text/javascript" src="app.js"></script>
</head>
<body>
	<h5>Exjs 6</h5>
</body>
</html>